In [3]:
import pandas as pd

df = pd.read_csv('../aggregate-reports/com.blockchain.btc.coinhub.csv')

In [4]:
df.head()

,pkg_name,repo_host,repo_path,repo_url,cited,origin,libarary_key,library_name,smali_prefix,fingerprint_types,classes_matched,sample_class,sample_class_file
0,com.blockchain.btc.coinhub,github.com,Kotlin/kotlinx.coroutines,https://github.com/Kotlin/kotlinx.coroutines,0,fingerprints,Kotlin/kotlinx.coroutines,kotlinx.coroutines,Landroid/os/,kotlin_package,1.0,Landroid/os/OutcomeReceiver;,data/decoded/com.blockchain.btc.coinhub/smali/...
1,com.blockchain.btc.coinhub,github.com,square/curtains,https://github.com/square/curtains,0,fingerprints,square/curtains,curtains,Landroid/view/,java_package,3.0,Landroid/view/ScrollCaptureCallback;,data/decoded/com.blockchain.btc.coinhub/smali/...
2,com.blockchain.btc.coinhub,github.com,mikepenz/FastAdapter,https://github.com/mikepenz/FastAdapter,0,fingerprints,mikepenz/FastAdapter,FastAdapter,Landroidx/recyclerview/widget/,kotlin_package,134.0,Landroidx/recyclerview/widget/GridLayoutManage...,data/decoded/com.blockchain.btc.coinhub/smali_...
3,com.blockchain.btc.coinhub,github.com,airbnb/lottie-android,https://github.com/airbnb/lottie-android,0,fingerprints,airbnb/lottie-android,lottie-android,Lcom/airbnb/lottie/,java_package,18.0,Lcom/airbnb/lottie/AsyncUpdates;,data/decoded/com.blockchain.btc.coinhub/smali_...
4,com.blockchain.btc.coinhub,github.com,sannies/mp4parser,https://github.com/sannies/mp4parser,0,fingerprints,sannies/mp4parser,mp4parser,Lcom/,java_package,37272.0,Lcom/airbnb/lottie/AsyncUpdates;,data/decoded/com.blockchain.btc.coinhub/smali_...

In [27]:
# I want all repo_urls that are cited, but not found in our license_exposure procedure
# Using these finding, I want to improve our license finding program
df[(df['cited'] == 1) & (df['origin'] == 'license_exposure') & (df['repo_url'].str.contains('github.com'))]

Empty DataFrame
Columns: [pkg_name, repo_host, repo_path, repo_url, cited, origin, libarary_key, library_name, smali_prefix, fingerprint_types, classes_matched, sample_class, sample_class_file]
Index: []

In [29]:
import pandas as pd
import glob
import os
import pandas as pd

# Set your target directory (change this to your path)
directory = "../aggregate-reports/"

# Find all CSV files in the directory
csv_files = glob.glob(os.path.join(directory, "*.csv"))

# Read and concatenate them into one DataFrame
all_data = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)

In [43]:
# I want all repo_urls that are cited, but not found in our license_exposure procedure
# Using these finding, I want to improve our license finding program
filtered_data = all_data[(all_data['cited'] == 1) & (all_data['origin'] == 'license_exposure') & (all_data['repo_url'].str.contains('github.com'))]

In [51]:
filtered_data.head(5)

,pkg_name,repo_host,repo_path,repo_url,cited,origin,libarary_key,library_name,smali_prefix,fingerprint_types,classes_matched,sample_class,sample_class_file
568,com.emed.s2p,NaN,NaN,https://github.com/google/dagger,1,license_exposure,google/dagger,google/dagger,NaN,generic_text_repo_url,NaN,NaN,data/decoded/com.emed.s2p/res/raw/onfido_licen...
1585,com.cwbank.mobileapp.prod,NaN,NaN,https://github.com/gionkunz/chartist-js,1,license_exposure,gionkunz/chartist-js,gionkunz/chartist-js,NaN,js_license_header,NaN,NaN,data/decoded/com.cwbank.mobileapp.prod/assets/...
1799,hu.webvalto.bkkfutar,NaN,NaN,https://github.com/google/accompanist/,1,license_exposure,accompanist-drawablepainter,accompanist-drawablepainter,NaN,json_license_heuristic,NaN,NaN,data/decoded/hu.webvalto.bkkfutar/assets/licen...
1800,hu.webvalto.bkkfutar,NaN,NaN,https://github.com/google/accompanist/,1,license_exposure,accompanist-navigation-material,accompanist-navigation-material,NaN,json_license_heuristic,NaN,NaN,data/decoded/hu.webvalto.bkkfutar/assets/licen...
1801,hu.webvalto.bkkfutar,NaN,NaN,https://github.com/google/accompanist/,1,license_exposure,accompanist-pager-indicators,accompanist-pager-indicators,NaN,json_license_heuristic,NaN,NaN,data/decoded/hu.webvalto.bkkfutar/assets/licen...

In [81]:
pkg_to_inspect = filtered_data[['pkg_name', 'repo_url']].drop_duplicates().reset_index(drop=True)

# add trailing slash
pkg_to_inspect['repo_url'] = pkg_to_inspect['repo_url'].apply(
    lambda url: url if url.endswith('/') else url + '/'
)

In [91]:
pkg_to_inspect.head(10)

,pkg_name,repo_url
0,com.emed.s2p,https://github.com/google/dagger/
1,com.cwbank.mobileapp.prod,https://github.com/gionkunz/chartist-js/
2,hu.webvalto.bkkfutar,https://github.com/google/accompanist/
3,hu.webvalto.bkkfutar,https://github.com/GoogleChrome/android-browse...
4,hu.webvalto.bkkfutar,https://github.com/google/dagger/
5,hu.webvalto.bkkfutar,https://github.com/square/curtains/
6,hu.webvalto.bkkfutar,https://github.com/square/okio/
7,hu.webvalto.bkkfutar,https://github.com/square/retrofit/
8,hu.webvalto.bkkfutar,https://github.com/square/wire/
9,hu.webvalto.bkkfutar,https://github.com/chrisbanes/snapper/

In [83]:
# Ok, it's we have "dagger" stored in our repo directory.
# Maybe our fingerprints.csv is not right
fp = pd.read_csv('../database/fingerprints.csv')
fp.head()

,repo_host,repo_path,repo_url,libarary_key,library_name,smali_prefix,fingerprint_type,repo_file_path,evidence_excerpt
0,github.com,EddyVerbruggen/SocialSharing-PhoneGap-Plugin,https://github.com/EddyVerbruggen/SocialSharin...,EddyVerbruggen/SocialSharing-PhoneGap-Plugin,SocialSharing-PhoneGap-Plugin,Lnl/xservices/plugins/,java_package,data/repos/github.com/EddyVerbruggen/SocialSha...,NaN
1,github.com,BoltsFramework/Bolts-Android,https://github.com/BoltsFramework/Bolts-Android,BoltsFramework/Bolts-Android,Bolts-Android,Lbolts/,java_package,data/repos/github.com/BoltsFramework/Bolts-And...,NaN
2,github.com,BoltsFramework/Bolts-Android,https://github.com/BoltsFramework/Bolts-Android,BoltsFramework/Bolts-Android,Bolts-Android,Lbolts/utils/,java_package,data/repos/github.com/BoltsFramework/Bolts-And...,NaN
3,github.com,BoltsFramework/Bolts-Android,https://github.com/BoltsFramework/Bolts-Android,BoltsFramework/Bolts-Android,Bolts-Android,Lbolts/android/,manifest_package,data/repos/github.com/BoltsFramework/Bolts-And...,NaN
4,github.com,BoltsFramework/Bolts-Android,https://github.com/BoltsFramework/Bolts-Android,BoltsFramework/Bolts-Android,Bolts-Android,Lbolts/test/,manifest_package,data/repos/github.com/BoltsFramework/Bolts-And...,NaN

In [84]:
# add trailing slash
fp['repo_url'] = fp['repo_url'].apply(
    lambda url: url if url.endswith('/') else url + '/'
)

In [85]:
# Now, cross check pkg_to_inspect and fingerprints
fp_intersect = set()

for r in pkg_to_inspect['repo_url'].unique():
    paths = fp.loc[fp['repo_url'] == r, 'repo_url'].unique()
    fp_intersect.update(paths)

print(fp_intersect)

{'https://github.com/sqlcipher/sqlcipher/', 'https://github.com/google/dagger/', 'https://github.com/square/wire/', 'https://github.com/socketio/socket.io-client-java/', 'https://github.com/coil-kt/coil/', 'https://github.com/square/okio/', 'https://github.com/google/accompanist/', 'https://github.com/react-native-datetimepicker/datetimepicker/', 'https://github.com/chrisbanes/snapper/', 'https://github.com/mattdesl/lwjgl-basics/', 'https://github.com/JetBrains/java-annotations/', 'https://github.com/aclassen/ComposeReorderable/', 'https://github.com/sqlcipher/android-database-sqlcipher/', 'https://github.com/jhy/jsoup/', 'https://github.com/square/curtains/', 'https://github.com/socketio/engine.io-client-java/', 'https://github.com/Kotlin/kotlinx.atomicfu/', 'https://github.com/JakeWharton/ThreeTenABP/', 'https://github.com/charpeni/react-native-url-polyfill/', 'https://github.com/DataDog/dd-trace-php/', 'https://github.com/square/retrofit/', 'https://github.com/openid/AppAuth-Android/', 'https://github.com/GoogleChrome/android-browser-helper/', 'https://github.com/Kotlin/kotlinx.collections.immutable/', 'https://github.com/driftyco/ionic/'}

In [86]:
# Collect file paths from pkg_to_inspect
pkg_paths = set()

for r in pkg_to_inspect['repo_url'].unique():
    paths = pkg_to_inspect.loc[pkg_to_inspect['repo_url'] == r, 'repo_url'].unique()
    pkg_paths.update(paths)

# Collect file paths from fp
fp_paths = set()

for r in pkg_to_inspect['repo_url'].unique():
    paths = fp.loc[fp['repo_url'] == r, 'repo_url'].unique()
    fp_paths.update(paths)

# Difference: paths in pkg_to_inspect but not in fp
diff_paths = pkg_paths - fp_paths
diff_paths

{'http://angular-ui.github.com/',
 'http://github.com/dpa99c/',
 'http://github.com/driftyco/ionic/',
 'http://github.com/necolas/normalize.css/',
 'https://github.com/Caligatio/jsSHA.git/',
 'https://github.com/KaTeX/KaTeX/',
 'https://github.com/Khan/perseus/',
 'https://github.com/Microsoft/TypeScript/',
 'https://github.com/MrRio/jsPDF/',
 'https://github.com/PolymerElements/paper-spinner/',
 'https://github.com/adobe-type-tools/cmap-resources/',
 'https://github.com/allenhwkim/angularjs-google-maps/',
 'https://github.com/angular-translate/angular-translate/',
 'https://github.com/angular-ui/ui-router/',
 'https://github.com/angular/angular.js/',
 'https://github.com/angular/material/',
 'https://github.com/ant-design/ant-design-icons/',
 'https://github.com/apvarun/toastify-js/',
 'https://github.com/ashtuchkin/iconv-lite/',
 'https://github.com/axios/axios/',
 'https://github.com/bitwiseshiftleft/sjcl/',
 'https://github.com/chriskempson/tomorrow-theme/',
 'https://github.com/cordova-sms/cordova-sms-plugin./',
 'https://github.com/csstree/csstree/',
 'https://github.com/douglascrockford/JSON-js/',
 'https://github.com/driftyco/ionic-cli/',
 'https://github.com/driftyco/ionic-platform-web-client/',
 'https://github.com/driftyco/ionicons/',
 'https://github.com/driftyco/ng-cordova/',
 'https://github.com/facebook/flow/',
 'https://github.com/gionkunz/chartist-js/',
 'https://github.com/gregjacobs/Autolinker.js/',
 'https://github.com/h5bp/html5-boilerplate/',
 'https://github.com/imaya/zlib.js/',
 'https://github.com/jhildenbiddle/css-vars-ponyfill/',
 'https://github.com/jquery/jquery-mobile/',
 'https://github.com/jrburke/requirejs/',
 'https://github.com/jsSHA/',
 'https://github.com/jsdoc3/jsdoc/',
 'https://github.com/mdn/data/',
 'https://github.com/mohayonao/inline-worker/',
 'https://github.com/necolas/normalize.css/',
 'https://github.com/ng2-ui/ng2-maps/',
 'https://github.com/nodeca/pica/',
 'https://github.com/ocombe/ocLazyLoad/',
 'https://github.com/philipwalton/flexbugs/',
 'https://github.com/philipwalton/solved-by-flexbox/',
 'https://github.com/rajeshwarpatlolla/ionic-ratings/',
 'https://github.com/react-native-community/discussions-and-proposals/',
 'https://github.com/sponsors/sindresorhus/',
 'https://github.com/stefanpenner/es6-promise/',
 'https://github.com/tildeio/rsvp.js/',
 'https://github.com/timdown/rangy/',
 'https://github.com/twbs/bootstrap/',
 'https://github.com/warpdesign/deferred-js#licence/',
 'https://github.com/zloirock/core-js/',
 "{'type': 'git', 'url': 'git+https://github.com/Caligatio/jsSHA.git'}/",
 "{'type': 'git', 'url': 'git+https://github.com/axios/axios.git'}/",
 "{'type': 'git', 'url': 'git+https://github.com/csstree/csstree.git'}/",
 "{'type': 'git', 'url': 'git+https://github.com/driftyco/ionic-platform-web-client.git'}/",
 "{'type': 'git', 'url': 'git+https://github.com/facebook/react-native.git'}/",
 "{'type': 'git', 'url': 'git+https://github.com/microsoft/react-native-code-push.git'}/",
 "{'type': 'git', 'url': 'git+https://github.com/software-mansion/react-native-reanimated.git'}/",
 "{'type': 'git', 'url': 'git+https://github.com/stripe/stripe-react-native.git'}/",
 "{'type': 'git', 'url': 'git://github.com/gregjacobs/Autolinker.js.git'}/",
 "{'type': 'git', 'url': 'https://github.com/Caligatio/jsSHA.git'}/",
 "{'type': 'git', 'url': 'https://github.com/angular/angular.js.git'}/",
 "{'type': 'git', 'url': 'https://github.com/charpeni/react-native-url-polyfill.git'}/",
 "{'type': 'git', 'url': 'https://github.com/microsoft/react-native-code-push'}/"}

In [90]:
fp[fp['repo_url'] == 'https://github.com/KaTeX/KaTeX/']

Empty DataFrame
Columns: [repo_host, repo_path, repo_url, libarary_key, library_name, smali_prefix, fingerprint_type, repo_file_path, evidence_excerpt]
Index: []